---
- hosts: 127.0.0.1
  connection: local
  become: true
  vars_files:
  - testsecret.yml
  environment:
       - "{{ env_vars }}"
  tasks:
   - name: apt-update
     apt:
      update_cache: yes
   - name: Create new directory
     file:
      path: /home/ubuntu/Deploy/
      state: directory   
   - name: Create new directory
     file:
      path: /home/ubuntu/Deploy/requirements/
      state: directory   
   - name: Copy the source code to hosts
     copy: src=./{{ item }} dest=/home/ubuntu/Deploy/
     with_items:
        - app
        - migrations
        - flasky.py
        - config.py
        - boot.sh
        - data-dev.sqlite
        - install.sh   
        - start.sh  
   - name: Copy the source code to hosts
     copy: src=./{{ item }} dest=/home/ubuntu/Deploy/requirements/
     with_items:
        - requirements/dev.txt       
        - requirements/common.txt  
   - name: Set up the environment 
     args:
       chdir: "/home/ubuntu/Deploy/"
     command: "{{ item }}"
     with_items:
        - chmod +x install.sh    
        - ./install.sh
   - name: Start environment
     args:
       chdir: "/home/ubuntu/Deploy/"
     command: "{{ item }}"
     with_items:
        - chmod +x start.sh
        - ./start.sh &
