---
- hosts: all
  become: true
  vars_files: testsecret.yml
  tasks:
   - name: apt-update
     apt:
      update_cache: yes
   - name: Install Docker
     apt:
      name: docker.io
      state: present
   - name: Create new directory
     file:
      path: /home/ubuntu/target
      state: directory
   - name: Copy the source code to hosts
     copy: src=./{{ item }} dest=/home/ubuntu/target/
     with_items:
        - app
        - migrations
        - flasky.py
        - config.py
        - boot.sh
        - data-dev.sqlite
        - Dockerfile
        - start.sh  
   - name: Copy the source code to hosts
     copy: src=./{{ item }} dest=/home/ubuntu/Deploy/requirements/
     with_items:
        - requirements 
   - name: current path
     command: pwd   
   - name: Build Docker Image
     command: chdir=/home/ubuntu/target docker build . --build-arg {{FLASK_APP}} --build-arg {{FLASK_CONFIG}} -t anjurose/inclass
   - name: Run Docker Container
     command: chdir=/home/ubuntu/target docker run -it -d -p 8085:5000 anjurose/inclass
