---
- hosts: 127.0.0.1
  connection: local
  become: true
  vars_files: testsecret.yml
  tasks:
   - name: apt-update
     apt:
      update_cache: yes
   - name: Install Docker
     apt:
      name: docker.io
      state: present
   - name: Create new directory
     file:
      path: /home/ubuntu/target
      state: directory
   - name: Copy the source code to hosts
     copy: src=./{{ item }} dest=/home/ubuntu/target/
     with_items:
        - app
        - migrations
        - flasky.py
        - config.py
        - boot.sh
        - data-dev.sqlite
        - Dockerfile
   - name: Copy the source code to hosts
     copy: src=./{{ item }} dest=/home/ubuntu/target/
     with_items:
        - requirements 
   - name: Install Docker
     apt:
      name: docker.io
      state: present
   - name: Build Docker Image
     command: chdir=/home/ubuntu/target/ sudo docker build . -t anjurose/inclass
   - name: Run Docker Container
     command: chdir=/home/ubuntu/target/ sudo docker run -it -d -p 8085:5000 anjurose/inclass
